# Generated by Django 3.2.3 on 2022-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regstray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('pname', models.CharField(blank=True, max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('local', models.EmailField(blank=True, max_length=20)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
    ]
