# Generated by Django 3.2.3 on 2022-03-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_regstray'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('date', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('number', models.IntegerField()),
                ('local', models.CharField(blank=True, max_length=122)),
            ],
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Animal',
        ),
    ]
