# Generated by Django 3.2.3 on 2022-03-20 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220320_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='Product',
        ),
    ]
